name: Deploy Action
run-name: ${{ github.actor }} is testing out ssh GitHub Actions ðŸš€
on: [push]
jobs:
  Build image and deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: 'sbt'
      - name: Build and push image
        run: sbt dockerBuildAndPush
      - name: Download image and restart container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_SECRET_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          username: ${{ secrets.SSH_USERNAME }}
          script: ls -la
